import type { Metadata } from "next";
import "./globals.css";

// AppProvider
import { AppProvider } from "@/providers/AppProvider";

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Toaster
import { Toaster } from "sonner";

// Cart
import { CartProvider } from "@/providers/CartProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AppProvider>
          <CartProvider>{children}</CartProvider>
        </AppProvider>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
